// List of regions/municipalities in Skopje
export const skopjeRegions = [
	{ value: "Центар", label: "Центар" },
	{ value: "Карпош", label: "Карпош" },
	{ value: "Аеродром", label: "Аеродром" },
	{ value: "Кисела Вода", label: "Кисела Вода" },
	{ value: "Водно", label: "Водно" },
	{ value: "Автокоманда", label: "Автокоманда" },
	{ value: "Арачиново", label: "Арачиново" },
	{ value: "Бардовци", label: "Бардовци" },
	{ value: "Бутел", label: "Бутел" },
	{ value: "Визбегово", label: "Визбегово" },
	{ value: "Влае", label: "Влае" },
	{ value: "Волково", label: "Волково" },
	{ value: "Гази Баба", label: "Гази Баба" },
	{ value: "Ѓорче Петров", label: "Ѓорче Петров" },
	{ value: "Железара", label: "Железара" },
	{ value: "Зелениково", label: "Зелениково" },
	{ value: "Илинден", label: "Илинден" },
	{ value: "Јурумлери", label: "Јурумлери" },
	{ value: "Катланово", label: "Катланово" },
	{ value: "Керамидница", label: "Керамидница" },
	{ value: "Козле", label: "Козле" },
	{ value: "Љуботен", label: "Љуботен" },
	{ value: "Маџари", label: "Маџари" },
	{ value: "Миладиновци", label: "Миладиновци" },
	{ value: "Нерези", label: "Нерези" },
	{ value: "Ново Село", label: "Ново Село" },
	{ value: "Орман", label: "Орман" },
	{ value: "Петровец", label: "Петровец" },
	{ value: "Припор", label: "Припор" },
	{ value: "Радишани", label: "Радишани" },
	{ value: "Раштак", label: "Раштак" },
	{ value: "Сарај", label: "Сарај" },
	{ value: "Скопје Север", label: "Скопје Север" },
	{ value: "Соње", label: "Соње" },
	{ value: "Сопиште", label: "Сопиште" },
	{ value: "Стајковци", label: "Стајковци" },
	{ value: "Студеничани", label: "Студеничани" },
	{ value: "Топанско Поле", label: "Топанско Поле" },
	{ value: "Трубарево", label: "Трубарево" },
	{ value: "Хиподром", label: "Хиподром" },
	{ value: "Чаир", label: "Чаир" },
	{ value: "Ченто", label: "Ченто" },
	{ value: "Чучер Сандево", label: "Чучер Сандево" },
	{ value: "Шуто Оризари", label: "Шуто Оризари" },
];

