import React, { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

export const useLanguage = () => {
	const context = useContext(LanguageContext);
	if (!context) {
		throw new Error("useLanguage must be used within a LanguageProvider");
	}
	return context;
};

// Translation data
const translations = {
	en: {
		// Header
		"nav.home": "Home",
		"nav.products": "Ads",
		"nav.sell": "Create Ad",
		"nav.profile": "Profile",
		"nav.about": "About",
		"nav.blog": "Blog",
		"nav.messages": "Messages",
		"nav.chat": "Chat",
		"nav.search.placeholder": "Search ads...",
		"nav.logo.subtitle": "Marketplace",

		// Home page
		"home.hero.title": "Welcome to NaDlanka",
		"home.hero.subtitle": "Your local marketplace for buying and selling items",
		"home.hero.browse": "Browse Ads",
		"home.hero.sell": "Sell Something",
		"home.stats.products": "Ads Available",
		"home.stats.users": "Active Users",
		"home.stats.free": "Free to Use",
		"home.categories.title": "Browse by Category",
		"home.categories.subtitle": "Find exactly what you're looking for",
		"home.categories.electronics": "Electronics",
		"home.categories.electronicsDesc": "Phones, laptops, gadgets",
		"home.categories.cars": "Cars & Vehicles",
		"home.categories.carsDesc": "Cars, motorcycles, parts",
		"home.categories.realEstate": "Real Estate",
		"home.categories.realEstateDesc": "Apartments, houses, land",
		"home.categories.furniture": "Furniture",
		"home.categories.furnitureDesc": "Home & office furniture",
		"home.categories.fashion": "Fashion",
		"home.categories.fashionDesc": "Clothing, shoes, accessories",
		"home.categories.services": "Services",
		"home.categories.servicesDesc": "Professional services",
		"home.exclusive.title": "Exclusive Ads",
		"home.featured.title": "Featured Ads",
		"home.featured.viewAll": "View All →",
		"home.featured.loading": "Loading featured ads...",
		"home.featured.noImage": "No Image",
		"home.howItWorks.title": "How NaDlanka Works",
		"home.howItWorks.step1.title": "Browse or Search",
		"home.howItWorks.step1.desc":
			"Find ads you're looking for using our search and filter system",
		"home.howItWorks.step2.title": "Contact Seller",
		"home.howItWorks.step2.desc":
			"Get in touch with the seller through their contact information",
		"home.howItWorks.step3.title": "Make a Deal",
		"home.howItWorks.step3.desc":
			"Negotiate and complete your transaction safely",
		"home.footer.tagline": "Your local marketplace",
		"home.footer.followUs": "Follow Us",
		"home.footer.rights": "All rights reserved.",

		// Common
		"common.loading": "Loading...",
		"common.error": "Error",
		"common.success": "Success",
		"common.email": "Email",
		"common.phone": "Phone",
		"common.save": "Save",
		"common.cancel": "Cancel",
		"common.edit": "Edit",
		"common.delete": "Delete",
		"common.view": "View",
		"common.price": "Price",
		"common.location": "Location",
		"common.category": "Category",
		"common.condition": "Condition",
		"common.description": "Description",
		"common.contact": "Contact",
		"common.seller": "Seller",
		"common.status": "Status",
		"common.views": "Views",
		"common.tags": "Tags",
		"common.currency.mkd": "MKD",
		"common.currency.eur": "EUR",
		"common.currency.usd": "USD",
		"common.or": "or",
		"common.phone": "Phone",
		"common.deleting": "Deleting...",

		// Category pages
		"category.subcategories": "Subcategories",
		"category.popularSearches": "Popular Searches",
		"category.filters": "Filters",
		"category.condition": "Condition",
		"category.allConditions": "All Conditions",
		"category.new": "New",
		"category.likeNew": "Like New",
		"category.good": "Good",
		"category.fair": "Fair",
		"category.priceRange": "Price Range",
		"category.minPrice": "Min",
		"category.maxPrice": "Max",
		"category.location": "Location",
		"category.enterLocation": "Enter location",
		"category.sortBy": "Sort by",
		"category.newestFirst": "Newest First",
		"category.oldestFirst": "Oldest First",
		"category.priceLowToHigh": "Price: Low to High",
		"category.priceHighToLow": "Price: High to Low",
		"category.mostPopular": "Most Popular",
		"category.clearFilters": "Clear All Filters",
		"category.itemsAvailable": "items available",
		"category.itemAvailable": "item available",
		"category.noProductsFound": "No ads found",
		"category.noProductsDesc":
			"Try adjusting your filters or create a listing for this category.",
		"category.createListing": "create a listing",
		"category.viewDetails": "View Details",
		"category.previous": "Previous",
		"category.next": "Next",
		"category.page": "Page",
		"category.of": "of",
		"category.wantToSell": "Want to sell in",
		"category.joinSellers": "Join thousands of sellers and reach more buyers",
		"category.startSelling": "Start Selling",

		// Category specific translations
		"category.electronics.title": "Electronics",
		"category.electronics.description":
			"Find the latest smartphones, laptops, gadgets and tech accessories",
		"category.electronics.subcategories.smartphones": "Smartphones",
		"category.electronics.subcategories.laptops": "Laptops",
		"category.electronics.subcategories.tablets": "Tablets",
		"category.electronics.subcategories.headphones": "Headphones",
		"category.electronics.subcategories.gaming": "Gaming",

		"category.cars.title": "Cars & Vehicles",
		"category.cars.description":
			"Buy and sell cars, motorcycles, and automotive accessories",
		"category.cars.subcategories.cars": "Cars",
		"category.cars.subcategories.motorcycles": "Motorcycles",
		"category.cars.subcategories.trucks": "Trucks",
		"category.cars.subcategories.parts": "Parts",
		"category.cars.subcategories.accessories": "Accessories",

		"category.realEstate.title": "Real Estate",
		"category.realEstate.description":
			"Apartments, houses, and commercial properties for sale and rent",
		"category.realEstate.subcategories.apartments": "Apartments",
		"category.realEstate.subcategories.houses": "Houses",
		"category.realEstate.subcategories.commercial": "Commercial",
		"category.realEstate.subcategories.land": "Land",
		"category.realEstate.subcategories.rentals": "Rentals",

		"category.furniture.title": "Furniture",
		"category.furniture.description":
			"Home and office furniture, decorations, and household items",
		"category.furniture.subcategories.livingRoom": "Living Room",
		"category.furniture.subcategories.bedroom": "Bedroom",
		"category.furniture.subcategories.kitchen": "Kitchen",
		"category.furniture.subcategories.office": "Office",
		"category.furniture.subcategories.outdoor": "Outdoor",

		"category.fashion.title": "Fashion & Clothing",
		"category.fashion.description":
			"Clothing, shoes, accessories, and fashion items for all seasons",
		"category.fashion.subcategories.mens": "Men's",
		"category.fashion.subcategories.womens": "Women's",
		"category.fashion.subcategories.kids": "Kids",
		"category.fashion.subcategories.shoes": "Shoes",
		"category.fashion.subcategories.accessories": "Accessories",

		"category.services.title": "Services",
		"category.services.description":
			"Professional services, tutoring, photography, and more",
		"category.services.subcategories.photography": "Photography",
		"category.services.subcategories.tutoring": "Tutoring",
		"category.services.subcategories.cleaning": "Cleaning",
		"category.services.subcategories.repair": "Repair",
		"category.services.subcategories.delivery": "Delivery",

		"category.sports.title": "Sports & Recreation",
		"category.sports.description":
			"Sports equipment, fitness gear, and recreational activities",
		"category.sports.subcategories.fitness": "Fitness",
		"category.sports.subcategories.outdoor": "Outdoor",
		"category.sports.subcategories.teamSports": "Team Sports",
		"category.sports.subcategories.waterSports": "Water Sports",
		"category.sports.subcategories.winterSports": "Winter Sports",

		"category.books.title": "Books & Education",
		"category.books.description":
			"Textbooks, novels, educational materials, and learning resources",
		"category.books.subcategories.textbooks": "Textbooks",
		"category.books.subcategories.novels": "Novels",
		"category.books.subcategories.childrens": "Children's",
		"category.books.subcategories.academic": "Academic",
		"category.books.subcategories.language": "Language",

		"category.homeGarden.title": "Home & Garden",
		"category.homeGarden.description":
			"Home improvement, garden tools, appliances, and household items",
		"category.homeGarden.subcategories.appliances": "Appliances",
		"category.homeGarden.subcategories.gardenTools": "Garden Tools",
		"category.homeGarden.subcategories.kitchen": "Kitchen",
		"category.homeGarden.subcategories.bathroom": "Bathroom",
		"category.homeGarden.subcategories.diy": "DIY",

		// Product detail page
		"product.yourListing": "This is your listing",
		"product.status.active": "Active",
		"product.status.inactive": "Inactive",
		"product.status.sold": "Sold",
		"product.yourDetails": "Your Details",
		"product.sellerInfo": "Seller Information",
		"product.viewYourProducts": "View Your Ads",
		"product.viewSellerProducts": "View Seller's Ads",
		"product.backToProducts": "Back to Ads",
		"product.contactSeller": "Contact Seller",
		"product.deactivate": "Deactivate",
		"product.activate": "Activate",
		"product.deleteConfirm":
			"Are you sure you want to delete this product? This action cannot be undone.",
		"product.deletedSuccess": "Ad deleted successfully",
		"product.deleteError": "Failed to delete ad. Please try again.",
		"product.statusError": "Failed to update ad status. Please try again.",
		"product.posted": "Posted",
		"product.editProduct": "Edit Ad",
		"product.backToProduct": "Back to Ad",

		// Contact functionality
		"contact.title": "Contact Seller",
		"contact.aboutProduct": "About this ad:",
		"contact.yourName": "Your Name",
		"contact.yourNamePlaceholder": "Enter your name",
		"contact.yourEmail": "Your Email",
		"contact.yourEmailPlaceholder": "Enter your email",
		"contact.message": "Message",
		"contact.messagePlaceholder": "Write your message to the seller...",
		"contact.sendMessage": "Send Message",
		"contact.sending": "Sending...",
		"contact.messageSent": "Message Sent!",
		"contact.messageSentDesc": "Your message has been sent to the seller.",
		"contact.chooseMethod": "How would you like to contact the seller?",
		"contact.methodDescription": "Choose between live chat or email:",
		"contact.liveChat": "Live Chat",
		"contact.liveChatDesc": "Instant messaging with real-time notifications",
		"contact.startChat": "Start Live Chat",
		"contact.chatDesc": "Chat in real-time with the seller",
		"contact.chatError": "Failed to start chat. Please try again.",
		"contact.loginForChat": "Please log in to use live chat",
		"contact.sendEmail": "Send Email",
		"contact.emailDesc": "Send a message via email (seller will be notified)",
		"contact.call": "Call",
		"contact.whatsapp": "WhatsApp",
		"contact.loginNotice": "You need to be logged in to use live chat.",

		// Favorites functionality
		"favorites.title": "My Favorites",
		"favorites.addToFavorites": "Add to favorites",
		"favorites.removeFromFavorites": "Remove from favorites",
		"favorites.save": "Save",
		"favorites.saved": "Saved",
		"favorites.noFavorites": "No favorites yet",
		"favorites.noFavoritesDesc":
			"Start saving your favorite ads to find them easily later.",
		"favorites.browseCatalogue": "Browse Catalogue",
		"favorites.error": "Failed to update favorites",
		"favorites.loading": "Loading favorites...",
		"favorites.totalFavorites": "Total Favorites",
		"favorites.viewAll": "View All Favorites",
		"favorites.loginToView": "Please log in to view your saved favorites",
		"auth.loginRequired": "Login Required",
		"auth.signIn": "Sign In",

		// Chat functionality
		"chat.title": "Chat",
		"chat.selectChat": "Select a chat to start messaging",
		"chat.selectChatDesc":
			"Choose a conversation from the sidebar to begin chatting.",
		"chat.newChat": "New Chat",
		"chat.search": "Search chats...",
		"chat.noChats": "No chats found",
		"chat.clearSearch": "Clear search",
		"chat.about": "About",
		"chat.noMessages": "No messages yet",
		"chat.typing": "is typing...",
		"chat.typeMessage": "Type a message...",
		"chat.loginRequired": "Please log in to use chat",
		"chat.loginRequiredDesc":
			"You need to be logged in to send and receive messages.",

		// Messages/Inbox functionality
		"messages.title": "Your Messages",
		"messages.all": "All Messages",
		"messages.unread": "Unread",
		"messages.read": "Read",
		"messages.replied": "Replied",
		"messages.noMessages": "No messages found",
		"messages.selectMessage": "Select a message to view details",
		"messages.contactInfo": "Contact Information",
		"messages.preferredContact": "Preferred Contact",
		"messages.message": "Message",
		"messages.reply": "Reply",
		"messages.replyInstruction":
			"Reply directly to this email address to contact the buyer.",
		"messages.replyEmail": "Reply via Email",
		"messages.markReplied": "Mark as Replied",
		"product.basicInfo": "Basic Information",
		"product.titlePlaceholder": "Enter ad title",
		"product.descriptionPlaceholder": "Describe your ad",
		"product.selectCategory": "Select Category",
		"product.selectCondition": "Select Condition",
		"product.additionalInfo": "Additional Information",
		"product.locationPlaceholder": "Enter location",
		"product.tagsPlaceholder": "Enter tags separated by commas",
		"product.tagsHelp":
			"Separate tags with commas (e.g., vintage, electronics, gaming)",
		"product.currentImages": "Current Images",
		"product.backToProfile": "Back to Profile",
		"product.updatedSuccess": "Ad updated successfully",
		"product.updateError": "Failed to update ad. Please try again.",
		"common.saving": "Saving...",

		// Ads page (Products/CreateProduct pages)
		"products.title": "All Ads",
		"products.search.placeholder": "Search ads...",
		"products.filter.category": "Category",
		"products.filter.condition": "Condition",
		"products.filter.priceRange": "Price Range",
		"products.filter.location": "Location",
		"products.filter.sortBy": "Sort by",
		"products.filter.sortBy.newest": "Newest",
		"products.filter.sortBy.oldest": "Oldest",
		"products.filter.sortBy.priceLow": "Price: Low to High",
		"products.filter.sortBy.priceHigh": "Price: High to Low",
		"products.filter.sortBy.views": "Most Viewed",
		"products.filter.clear": "Clear Filters",
		"products.noResults": "No ads found",
		"products.loading": "Loading ads...",
		"products.error": "Error loading ads",
		"products.pagination.previous": "Previous",
		"products.pagination.next": "Next",
		"products.pagination.page": "Page",
		"products.pagination.of": "of",
		"products.showMore": "Show More Ads",

		// Product Detail page
		"productDetail.title": "Ad Details",
		"productDetail.seller": "Seller",
		"productDetail.contact": "Contact Seller",
		"productDetail.description": "Description",
		"productDetail.condition": "Condition",
		"productDetail.category": "Category",
		"productDetail.location": "Location",
		"productDetail.views": "views",
		"productDetail.tags": "Tags",
		"productDetail.status": "Status",
		"productDetail.status.available": "Available",
		"productDetail.status.sold": "Sold",
		"productDetail.status.pending": "Pending",
		"productDetail.backToProducts": "Back to Ads",
		"productDetail.editProduct": "Edit Ad",
		"productDetail.deleteProduct": "Delete Ad",
		"productDetail.confirmDelete":
			"Are you sure you want to delete this product?",
		"productDetail.deleteSuccess": "Ad deleted successfully",
		"productDetail.deleteError": "Error deleting ad",

		// Create Product page
		"createProduct.title": "Create New Ad",
		"createProduct.editTitle": "Edit Ad",
		"createProduct.form.title": "Ad Title",
		"createProduct.form.title.placeholder": "Enter ad title",
		"createProduct.form.description": "Description",
		"createProduct.form.description.placeholder": "Describe your ad...",
		"createProduct.form.price": "Price",
		"createProduct.form.currency": "Currency",
		"createProduct.form.category": "Category",
		"createProduct.form.condition": "Condition",
		"createProduct.form.status": "Status",
		"createProduct.form.location": "Location",
		"createProduct.form.location.placeholder": "Enter location",
		"createProduct.form.basicInfo": "Basic Information",
		"createProduct.form.contactInfo": "Contact Information",
		"createProduct.form.contactInfo.placeholder":
			"Phone, email, or other contact info",
		"createProduct.form.tags": "Tags",
		"createProduct.form.tags.placeholder": "Enter tags separated by commas",
		"createProduct.form.images": "Ad Images",
		"createProduct.form.images.upload": "Upload Images",
		"createProduct.form.images.remove": "Remove",
		"createProduct.form.submit": "Create Ad",
		"createProduct.form.update": "Update Ad",
		"createProduct.form.cancel": "Cancel",
		"createProduct.success": "Ad created successfully!",
		"createProduct.updateSuccess": "Ad updated successfully!",
		"createProduct.error": "Error creating ad",
		"createProduct.updateError": "Error updating ad",
		"createProduct.validation.titleRequired": "Title is required",
		"createProduct.validation.descriptionRequired": "Description is required",
		"createProduct.validation.priceRequired": "Price is required",
		"createProduct.validation.pricePositive": "Price must be positive",
		"createProduct.validation.categoryRequired": "Category is required",
		"createProduct.validation.conditionRequired": "Condition is required",
		"createProduct.validation.locationRequired": "Location is required",
		"createProduct.invalidPhone":
			"Please enter a valid North Macedonia phone number (e.g., +389 XX XXX XXX or 0XX XXX XXX)",
		"createProduct.invalidPhoneFormat":
			"Please enter a valid North Macedonia phone number",

		// Category-specific fields
		"createProduct.categoryType.title": "Category Type",
		"createProduct.categoryType.description":
			"Select the type of ad you want to create to see relevant fields",
		"createProduct.categoryType.general": "General Ad",
		"createProduct.categoryType.generalDesc":
			"Standard form for all categories",
		"createProduct.categoryType.realEstate": "Real Estate",
		"createProduct.categoryType.realEstateDesc":
			"Property details, area, address, bedrooms",
		"createProduct.categoryType.cars": "Cars & Vehicles",
		"createProduct.categoryType.carsDesc":
			"Year, mileage, fuel type, transmission",

		// Real Estate specific fields
		"createProduct.realEstate.title": "Property Details",
		"createProduct.realEstate.propertyType": "Property Type",
		"createProduct.realEstate.propertyType.apartment": "Apartment",
		"createProduct.realEstate.propertyType.house": "House",
		"createProduct.realEstate.propertyType.land": "Land",
		"createProduct.realEstate.propertyType.commercial": "Commercial",
		"createProduct.realEstate.area": "Area (m²)",
		"createProduct.realEstate.area.placeholder": "e.g., 120",
		"createProduct.realEstate.address": "Property Address",
		"createProduct.realEstate.address.placeholder": "Full property address",
		"createProduct.realEstate.bedrooms": "Bedrooms",
		"createProduct.realEstate.bathrooms": "Bathrooms",

		// Car specific fields
		"createProduct.cars.title": "Vehicle Details",
		"createProduct.cars.year": "Year",
		"createProduct.cars.year.placeholder": "e.g., 2020",
		"createProduct.cars.mileage": "Mileage (km)",
		"createProduct.cars.mileage.placeholder": "e.g., 50000",
		"createProduct.cars.fuelType": "Fuel Type",
		"createProduct.cars.fuelType.petrol": "Petrol",
		"createProduct.cars.fuelType.diesel": "Diesel",
		"createProduct.cars.fuelType.electric": "Electric",
		"createProduct.cars.fuelType.hybrid": "Hybrid",
		"createProduct.cars.transmission": "Transmission",
		"createProduct.cars.transmission.manual": "Manual",
		"createProduct.cars.transmission.automatic": "Automatic",
		"createProduct.cars.color": "Color",
		"createProduct.cars.color.placeholder": "e.g., Silver, Black, White",

		// Common select options
		"createProduct.select.propertyType": "Select property type",
		"createProduct.select.bedrooms": "Select bedrooms",
		"createProduct.select.bathrooms": "Select bathrooms",
		"createProduct.select.fuelType": "Select fuel type",
		"createProduct.select.transmission": "Select transmission",
		"createProduct.select.condition": "Select condition",
		"createProduct.select.category": "Select category",

		// Profile page
		"profile.title": "My Profile",
		"profile.editProfile": "Edit Profile",
		"profile.saveChanges": "Save Changes",
		"profile.cancel": "Cancel",
		"profile.personalInfo": "Personal Information",
		"profile.name": "Name",
		"profile.email": "Email",
		"profile.phone": "Phone",
		"profile.location": "Location",
		"profile.bio": "Bio",
		"profile.bio.placeholder": "Tell us about yourself...",
		"profile.myProducts": "My Ads",
		"profile.noProducts": "You haven't created any ads yet",
		"profile.createFirst": "Create Your First Ad",
		"profile.stats": "Statistics",
		"profile.totalProducts": "Total Ads",
		"profile.totalViews": "Total Views",
		"profile.success": "Profile updated successfully!",
		"profile.error": "Error updating profile",

		// About page
		"about.title": "About NaDlanka",
		"about.subtitle": "Your Local Marketplace",
		"about.mission": "Our Mission",
		"about.mission.text":
			"To connect local communities through a simple, secure, and user-friendly marketplace platform that makes buying and selling items effortless.",
		"about.features": "Why Choose NaDlanka?",
		"about.feature1.title": "Local & Trusted",
		"about.feature1.desc":
			"Connect with people in your community for safe, local transactions.",
		"about.feature2.title": "Easy to Use",
		"about.feature2.desc":
			"Simple interface designed for everyone, regardless of technical experience.",
		"about.feature3.title": "Completely Free",
		"about.feature3.desc":
			"No fees, no hidden costs. List and browse products for free.",
		"about.feature4.title": "Secure Platform",
		"about.feature4.desc": "Your safety and privacy are our top priorities.",
		"about.team": "Our Team",
		"about.team.text":
			"We're a passionate team dedicated to building the best local marketplace experience.",
		"about.contact": "Get in Touch",
		"about.contact.text":
			"Have questions or suggestions? We'd love to hear from you!",
		"about.contact.email": "Email us",
		"about.contact.phone": "Call us",
		"about.footer":
			"Join thousands of users who trust NaDlanka for their local marketplace needs.",

		// Categories
		"categories.all": "All Categories",
		"categories.electronics": "Electronics",
		"categories.furniture": "Furniture",
		"categories.cars": "Cars",
		"categories.realEstate": "Real Estate",
		"categories.fashion": "Fashion",
		"categories.books": "Books",
		"categories.sports": "Sports",
		"categories.homeGarden": "Home & Garden",
		"categories.services": "Services",
		"categories.other": "Other",

		// Conditions
		"conditions.all": "All Conditions",
		"conditions.new": "New",
		"conditions.like_new": "Like New",
		"conditions.very_good": "Very Good",
		"conditions.good": "Good",
		"conditions.fair": "Fair",
		"conditions.poor": "Poor",

		// Form labels
		"form.min": "Min",
		"form.max": "Max",
		"form.enterLocation": "Enter location...",
		"form.productsFound": "ads found",
		"form.nameAZ": "Name: A to Z",
		"form.by": "By",

		// Authentication
		"auth.login.title": "Welcome Back",
		"auth.login.subtitle": "Sign in to your account",
		"auth.login.button": "Sign In",
		"auth.login.noAccount": "Don't have an account?",
		"auth.login.registerLink": "Sign up",
		"auth.register.title": "Create Account",
		"auth.register.subtitle": "Join NaDlanka today",
		"auth.register.button": "Sign Up",
		"auth.register.hasAccount": "Already have an account?",
		"auth.register.loginLink": "Sign in",
		"auth.register.passwordMismatch": "Passwords do not match",
		"auth.register.passwordTooShort": "Password must be at least 6 characters",
		"auth.email": "Email",
		"auth.password": "Password",
		"auth.confirmPassword": "Confirm Password",
		"auth.name": "Full Name",
		"auth.phone": "Phone Number",
		"auth.location": "Location",
		"auth.emailPlaceholder": "Enter your email",
		"auth.passwordPlaceholder": "Enter your password",
		"auth.confirmPasswordPlaceholder": "Confirm your password",
		"auth.namePlaceholder": "Enter your full name",
		"auth.phonePlaceholder": "Enter your phone number",
		"auth.locationPlaceholder": "Enter your location",
		"auth.loggingIn": "Signing in...",
		"auth.registering": "Creating account...",
		"auth.logout": "Sign Out",
		"auth.google.signIn": "Sign in with Google",
		"auth.google.signUp": "Sign up with Google",
		"auth.google.continue": "Continue with Google",

		// Profile
		"profile.addProduct": "Add Ad",
		"profile.myProducts": "My Ads",
		"profile.statistics": "Statistics",
		"profile.noProducts": "No ads yet",
		"profile.startSelling":
			"Start selling by creating your first product listing.",
		"profile.createFirstProduct": "Create First Ad",
		"profile.totalProducts": "Total Ads",
		"profile.activeListings": "Active Listings",
		"profile.totalViews": "Total Views",
		"profile.soldItems": "Sold Items",
		"profile.recentActivity": "Recent Activity",
		"profile.noActivity": "No activity yet",
		"profile.settings": "Settings",
		"profile.profileSettings": "Profile Settings",
		"profile.profileSettingsDesc":
			"Update your personal information and contact details.",
		"profile.invalidPhone":
			"Please enter a valid North Macedonia phone number (e.g., +389 XX XXX XXX or 0XX XXX XXX)",
		"profile.invalidPhoneFormat":
			"Please enter a valid North Macedonia phone number",
		"profile.updateSuccess": "Profile updated successfully!",
		"profile.updateError": "Failed to update profile",
		"profile.locationPlaceholder": "City, Country",

		// Common
		"common.loading": "Loading...",
		"common.view": "View",
		"common.edit": "Edit",

		// Blog
		"blog.title": "NaDlanka Blog",
		"blog.subtitle": "Tips, guides, and insights for buying and selling",
		"blog.featured": "Featured Posts",
		"blog.browseByCategory": "Browse by Category",
		"blog.allCategories": "All Categories",
		"blog.categories.tips": "Tips & Guides",
		"blog.categories.news": "Market News",
		"blog.categories.stories": "Success Stories",
		"blog.categories.safety": "Safety & Security",
		"blog.categories.local": "Local News",
		"blog.readMore": "Read More",
		"blog.likes": "likes",
		"blog.minRead": "min read",
		"blog.noPosts": "No posts found in this category.",
		"blog.recentPosts": "Recent Posts",
		"blog.categories": "Categories",
		"blog.popularTags": "Popular Tags",
		"blog.newsletter": "Stay Updated",
		"blog.newsletterDesc":
			"Get the latest tips and market updates delivered to your inbox.",
		"blog.emailPlaceholder": "Enter your email",
		"blog.subscribe": "Subscribe",
		"blog.error": "Error Loading Blog",
	},

	sq: {
		// Header
		"nav.home": "Kryefaqja",
		"nav.products": "Oglaset",
		"nav.sell": "Krijo reklamë",
		"nav.profile": "Profili",
		"nav.about": "Rreth nesh",
		"nav.blog": "Blogu",
		"nav.messages": "Mesazhet",
		"nav.chat": "Biseda",
		"nav.search.placeholder": "Kërko oglase...",
		"nav.logo.subtitle": "Tregu",

		// Home page
		"home.hero.title": "Mirë se vini në NaDlanka",
		"home.hero.subtitle": "Tregu juaj lokal për blerje dhe shitje oglasësh",
		"home.hero.browse": "Shiko Oglase",
		"home.hero.sell": "Shit Diçka",
		"home.stats.products": "Oglase të Disponueshme",
		"home.stats.users": "Përdorues Aktivë",
		"home.stats.free": "Falas për të Përdorur",
		"home.categories.title": "Shfletoni sipas Kategorisë",
		"home.categories.subtitle": "Gjeni pikërisht atë që kërkoni",
		"home.categories.electronics": "Elektronika",
		"home.categories.electronicsDesc": "Telefona, laptopë, pajisje",
		"home.categories.cars": "Makinat dhe Automjetet",
		"home.categories.carsDesc": "Makinat, motorët, pjesë",
		"home.categories.realEstate": "Pasuri të Paluajtshme",
		"home.categories.realEstateDesc": "Apartamente, shtëpi, tokë",
		"home.categories.furniture": "Mobilje",
		"home.categories.furnitureDesc": "Mobilje për shtëpi dhe zyrë",
		"home.categories.fashion": "Moda",
		"home.categories.fashionDesc": "Veshje, këpucë, aksesorë",
		"home.categories.services": "Shërbimet",
		"home.categories.servicesDesc": "Shërbime profesionale",
		"home.exclusive.title": "Oglase Ekskluzive",
		"home.featured.title": "Oglase të Veçanta",
		"home.featured.viewAll": "Shiko të Gjitha →",
		"home.featured.loading": "Duke ngarkuar oglaset e veçanta...",
		"home.featured.noImage": "Nuk ka Imazh",
		"home.howItWorks.title": "Si Funksionon NaDlanka",
		"home.howItWorks.step1.title": "Shiko ose Kërko",
		"home.howItWorks.step1.desc":
			"Gjej oglaset që po kërkon duke përdorur sistemin tonë të kërkimit dhe filtrimit",
		"home.howItWorks.step2.title": "Kontakto Shitësin",
		"home.howItWorks.step2.desc":
			"Lidhu me shitësin përmes informacioneve të kontaktit të tij",
		"home.howItWorks.step3.title": "Bëj një Marrëveshje",
		"home.howItWorks.step3.desc":
			"Negocio dhe përfundo transaksionin tënd në mënyrë të sigurt",
		"home.footer.tagline": "Tregu juaj lokal",
		"home.footer.followUs": "Na Ndiqni",
		"home.footer.rights": "Të gjitha të drejtat e rezervuara.",

		// Common
		"common.loading": "Duke ngarkuar...",
		"common.error": "Gabim",
		"common.success": "Sukses",
		"common.save": "Ruaj",
		"common.cancel": "Anulo",
		"common.edit": "Ndrysho",
		"common.delete": "Fshi",
		"common.view": "Shiko",
		"common.price": "Çmimi",
		"common.location": "Vendndodhja",
		"common.category": "Kategoria",
		"common.condition": "Gjendja",
		"common.description": "Përshkrimi",
		"common.contact": "Kontakti",
		"common.seller": "Shitësi",
		"common.status": "Statusi",
		"common.views": "Shikime",
		"common.tags": "Etiketat",
		"common.currency.mkd": "MKD",
		"common.currency.eur": "EUR",
		"common.currency.usd": "USD",
		"common.or": "ose",
		"common.phone": "Telefoni",
		"common.email": "Email",
		"common.deleting": "Po fshihet...",

		// Category pages
		"category.subcategories": "Nënkategoritë",
		"category.popularSearches": "Kërkimet Popullore",
		"category.filters": "Filtrat",
		"category.condition": "Gjendja",
		"category.allConditions": "Të Gjitha Gjendjet",
		"category.new": "E Re",
		"category.likeNew": "Si E Re",
		"category.good": "E Mirë",
		"category.fair": "E Pranueshme",
		"category.priceRange": "Gama e Çmimeve",
		"category.minPrice": "Min",
		"category.maxPrice": "Max",
		"category.location": "Vendndodhja",
		"category.enterLocation": "Vendosni vendndodhjen",
		"category.sortBy": "Rendit sipas",
		"category.newestFirst": "Më të Rejat Së Pari",
		"category.oldestFirst": "Më të Vjetrat Së Pari",
		"category.priceLowToHigh": "Çmimi: Nga i Uli në të Lartë",
		"category.priceHighToLow": "Çmimi: Nga i Larti në të Ulët",
		"category.mostPopular": "Më të Popullarizuarat",
		"category.clearFilters": "Pastro Të Gjitha Filtrat",
		"category.itemsAvailable": "artikuj të disponueshëm",
		"category.itemAvailable": "artikull i disponueshëm",
		"category.noProductsFound": "Nuk u gjetën oglase",
		"category.noProductsDesc":
			"Provoni të rregulloni filtrat tuaj ose krijoni një listim për këtë kategori.",
		"category.createListing": "krijoni një listim",
		"category.viewDetails": "Shiko Detajet",
		"category.previous": "Paraardhës",
		"category.next": "Tjetër",
		"category.page": "Faqja",
		"category.of": "nga",
		"category.wantToSell": "Dëshiron të shesësh në",
		"category.joinSellers":
			"Bashkohu me mijëra shitës dhe arri më shumë blerës",
		"category.startSelling": "Fillo të Shish",

		// Category specific translations
		"category.electronics.title": "Elektronika",
		"category.electronics.description":
			"Gjeni telefonat e fundit, laptopët, pajisjet dhe aksesorët teknologjikë",
		"category.electronics.subcategories.smartphones": "Smartphone",
		"category.electronics.subcategories.laptops": "Laptopë",
		"category.electronics.subcategories.tablets": "Tableta",
		"category.electronics.subcategories.headphones": "Kufje",
		"category.electronics.subcategories.gaming": "Lojëra",

		"category.cars.title": "Makinat & Automjetet",
		"category.cars.description":
			"Bleni dhe shisni makinat, motoçikletat dhe aksesorët automobilistikë",
		"category.cars.subcategories.cars": "Makinat",
		"category.cars.subcategories.motorcycles": "Motoçikletat",
		"category.cars.subcategories.trucks": "Kamionët",
		"category.cars.subcategories.parts": "Pjesët",
		"category.cars.subcategories.accessories": "Aksesorët",

		"category.realEstate.title": "Pasuritë e Paluajtshme",
		"category.realEstate.description":
			"Apartamentet, shtëpitë dhe pasuritë tregtare për shitje dhe qira",
		"category.realEstate.subcategories.apartments": "Apartamentet",
		"category.realEstate.subcategories.houses": "Shtëpitë",
		"category.realEstate.subcategories.commercial": "Tregtare",
		"category.realEstate.subcategories.land": "Tokat",
		"category.realEstate.subcategories.rentals": "Qira",

		"category.furniture.title": "Mobiljet",
		"category.furniture.description":
			"Mobiljet e shtëpisë dhe zyrës, dekorimet dhe sendet e shtëpisë",
		"category.furniture.subcategories.livingRoom": "Dhoma e Ditarit",
		"category.furniture.subcategories.bedroom": "Dhoma e Gjumit",
		"category.furniture.subcategories.kitchen": "Kuzhina",
		"category.furniture.subcategories.office": "Zyra",
		"category.furniture.subcategories.outdoor": "Jashtë",

		"category.fashion.title": "Moda & Veshje",
		"category.fashion.description":
			"Veshjet, këpucët, aksesorët dhe sendet e modës për të gjitha stinët",
		"category.fashion.subcategories.mens": "Meshkuj",
		"category.fashion.subcategories.womens": "Femra",
		"category.fashion.subcategories.kids": "Fëmijë",
		"category.fashion.subcategories.shoes": "Këpucët",
		"category.fashion.subcategories.accessories": "Aksesorët",

		"category.services.title": "Shërbimet",
		"category.services.description":
			"Shërbimet profesionale, mësimdhënia, fotografia dhe më shumë",
		"category.services.subcategories.photography": "Fotografia",
		"category.services.subcategories.tutoring": "Mësimdhënia",
		"category.services.subcategories.cleaning": "Pastrimi",
		"category.services.subcategories.repair": "Riparimi",
		"category.services.subcategories.delivery": "Dërgimi",

		"category.sports.title": "Sporti & Rekreacioni",
		"category.sports.description":
			"Pajisjet sportive, pajisjet e fitnesit dhe aktivitetet rekreative",
		"category.sports.subcategories.fitness": "Fitnesi",
		"category.sports.subcategories.outdoor": "Jashtë",
		"category.sports.subcategories.teamSports": "Sportet e Ekipit",
		"category.sports.subcategories.waterSports": "Sportet e Ujit",
		"category.sports.subcategories.winterSports": "Sportet e Dimrit",

		"category.books.title": "Librat & Arsimi",
		"category.books.description":
			"Libra shkollorë, romane, materiale arsimore dhe burime mësimore",
		"category.books.subcategories.textbooks": "Libra Shkollorë",
		"category.books.subcategories.novels": "Romane",
		"category.books.subcategories.childrens": "Fëmijë",
		"category.books.subcategories.academic": "Akademik",
		"category.books.subcategories.language": "Gjuha",

		"category.homeGarden.title": "Shtëpia & Kopshti",
		"category.homeGarden.description":
			"Përmirësimi i shtëpisë, mjetet e kopshtit, elektroshtëpitë dhe sendet e shtëpisë",
		"category.homeGarden.subcategories.appliances": "Elektroshtëpitë",
		"category.homeGarden.subcategories.gardenTools": "Mjetet e Kopshtit",
		"category.homeGarden.subcategories.kitchen": "Kuzhina",
		"category.homeGarden.subcategories.bathroom": "Banjoja",
		"category.homeGarden.subcategories.diy": "Bëj Vetë",

		// Product detail page
		"product.yourListing": "Ky është listimi juaj",
		"product.status.active": "Aktiv",
		"product.status.inactive": "Joaktiv",
		"product.status.sold": "I shitur",
		"product.yourDetails": "Detajet tuaja",
		"product.sellerInfo": "Informacioni i shitësit",
		"product.viewYourProducts": "Shiko oglaset tuaja",
		"product.viewSellerProducts": "Shiko produktet e shitësit",
		"product.backToProducts": "Kthehu te oglaset",
		"product.contactSeller": "Kontakto shitësin",
		"product.deactivate": "Deaktivizo",
		"product.activate": "Aktivizo",
		"product.deleteConfirm":
			"A jeni të sigurt që doni të fshini këtë produkt? Ky veprim nuk mund të anulohet.",
		"product.deletedSuccess": "Produkti u fshi me sukses",
		"product.deleteError":
			"Dështoi fshirja e produktit. Ju lutemi provoni përsëri.",
		"product.statusError":
			"Dështoi përditësimi i statusit të produktit. Ju lutemi provoni përsëri.",
		"product.posted": "Postuar",
		"product.editProduct": "Redakto Produktin",
		"product.backToProduct": "Kthehu te Produkti",

		// Contact functionality
		"contact.title": "Kontakto Shitësin",
		"contact.aboutProduct": "Rreth këtij produkti:",
		"contact.yourName": "Emri Juaj",
		"contact.yourNamePlaceholder": "Shkruani emrin tuaj",
		"contact.yourEmail": "Email-i Juaj",
		"contact.yourEmailPlaceholder": "Shkruani email-in tuaj",
		"contact.message": "Mesazhi",
		"contact.messagePlaceholder": "Shkruani mesazhin tuaj për shitësin...",
		"contact.sendMessage": "Dërgo Mesazhin",
		"contact.sending": "Duke dërguar...",
		"contact.messageSent": "Mesazhi u Dërgua!",
		"contact.messageSentDesc": "Mesazhi juaj u dërgua te shitësi.",
		"contact.chooseMethod": "Si dëshironi të kontaktoni shitësin?",
		"contact.methodDescription":
			"Zgjidhni midis bisedës së drejtpërdrejtë ose email-it:",
		"contact.liveChat": "Bisedë e Drejtpërdrejtë",
		"contact.liveChatDesc": "Mesazhe të menjëhershme me njoftime në kohë reale",
		"contact.startChat": "Fillo Bisedën e Drejtpërdrejtë",
		"contact.chatDesc": "Bisedoni në kohë reale me shitësin",
		"contact.chatError":
			"Dështoi fillimi i bisedës. Ju lutemi provoni përsëri.",
		"contact.loginForChat":
			"Ju lutemi regjistrohuni për të përdorur bisedën e drejtpërdrejtë",
		"contact.sendEmail": "Dërgo Email",
		"contact.emailDesc":
			"Dërgo një mesazh nëpërmjet email-it (shitësi do të njoftohet)",
		"contact.call": "Telefono",
		"contact.whatsapp": "WhatsApp",
		"contact.loginNotice":
			"Duhet të jeni të regjistruar për të përdorur bisedën e drejtpërdrejtë.",

		// Favorites functionality
		"favorites.title": "Të preferuarat e mia",
		"favorites.addToFavorites": "Shto në të preferuarat",
		"favorites.removeFromFavorites": "Hiq nga të preferuarat",
		"favorites.save": "Ruaj",
		"favorites.saved": "I ruajtur",
		"favorites.noFavorites": "Ende nuk ka të preferuara",
		"favorites.noFavoritesDesc":
			"Filloni të ruani oglaset tuaja të preferuara për t'i gjetur lehtësisht më vonë.",
		"favorites.browseCatalogue": "Shfleto Katalogun",
		"favorites.error": "Dështoi përditësimi i të preferuarave",
		"favorites.loading": "Duke u ngarkuar të preferuarat...",
		"favorites.totalFavorites": "Totali i të preferuarave",
		"favorites.viewAll": "Shiko të gjitha të preferuarat",
		"favorites.loginToView":
			"Ju lutemi identifikohuni për të parë të preferuarat tuaja",
		"auth.loginRequired": "Nevojitet hyrje",
		"auth.signIn": "Hyr",

		// Chat functionality
		"chat.title": "Biseda",
		"chat.selectChat": "Zgjidhni një bisedë për të filluar mesazhet",
		"chat.selectChatDesc":
			"Zgjidhni një bisedë nga paneli anësor për të filluar të bisedoni.",
		"chat.newChat": "Bisedë e Re",
		"chat.search": "Kërko biseda...",
		"chat.noChats": "Nuk u gjetën biseda",
		"chat.clearSearch": "Pastro kërkimin",
		"chat.about": "Rreth",
		"chat.noMessages": "Ende nuk ka mesazhe",
		"chat.typing": "po shkruan...",
		"chat.typeMessage": "Shkruani një mesazh...",
		"chat.loginRequired": "Ju lutemi regjistrohuni për të përdorur bisedën",
		"chat.loginRequiredDesc":
			"Duhet të jeni të regjistruar për të dërguar dhe marrë mesazhe.",

		// Messages/Inbox functionality
		"messages.title": "Mesazhet Tuaja",
		"messages.all": "Të Gjitha Mesazhet",
		"messages.unread": "Të Palexuar",
		"messages.read": "Të Lexuar",
		"messages.replied": "Të Përgjigjur",
		"messages.noMessages": "Nuk u gjetën mesazhe",
		"messages.selectMessage": "Zgjidhni një mesazh për të parë detajet",
		"messages.contactInfo": "Informacioni i Kontaktit",
		"messages.preferredContact": "Kontakti i Preferuar",
		"messages.message": "Mesazhi",
		"messages.reply": "Përgjigju",
		"messages.replyInstruction":
			"Përgjigjuni drejtpërdrejt kësaj adrese email për të kontaktuar blerësin.",
		"messages.replyEmail": "Përgjigju nëpërmjet Email-it",
		"messages.markReplied": "Shëno si të Përgjigjur",
		"product.basicInfo": "Informacioni Bazik",
		"product.titlePlaceholder": "Vendos titullin e produktit",
		"product.descriptionPlaceholder": "Përshkruani produktin tuaj",
		"product.selectCategory": "Zgjidh Kategorinë",
		"product.selectCondition": "Zgjidh Gjendjen",
		"product.additionalInfo": "Informacioni Shtesë",
		"product.locationPlaceholder": "Vendos lokacionin",
		"product.tagsPlaceholder": "Vendos etiketat të ndara me presje",
		"product.tagsHelp":
			"Ndani etiketat me presje (p.sh., vintage, elektronikë, lojëra)",
		"product.currentImages": "Imazhet Aktuale",
		"product.backToProfile": "Kthehu te Profili",
		"product.updatedSuccess": "Produkti u përditësua me sukses",
		"product.updateError":
			"Dështoi përditësimi i produktit. Ju lutemi provoni përsëri.",
		"common.saving": "Po ruhet...",

		// Ads page (Products/CreateProduct pages)
		"products.title": "Të Gjitha Oglaset",
		"products.search.placeholder": "Kërko oglase...",
		"products.filter.category": "Kategoria",
		"products.filter.condition": "Gjendja",
		"products.filter.priceRange": "Gama e Çmimit",
		"products.filter.location": "Vendndodhja",
		"products.filter.sortBy": "Rendit sipas",
		"products.filter.sortBy.newest": "Më të Rejat",
		"products.filter.sortBy.oldest": "Më të Vjetrat",
		"products.filter.sortBy.priceLow": "Çmimi: Nga i Uli në i Larti",
		"products.filter.sortBy.priceHigh": "Çmimi: Nga i Larti në i Uli",
		"products.filter.sortBy.views": "Më të Shikuarat",
		"products.filter.clear": "Pastro Filtra",
		"products.noResults": "Nuk u gjetën oglase",
		"products.loading": "Duke ngarkuar produktet...",
		"products.error": "Gabim në ngarkimin e produkteve",
		"products.pagination.previous": "Mëparshme",
		"products.pagination.next": "Tjetra",
		"products.pagination.page": "Faqja",
		"products.pagination.of": "nga",
		"products.showMore": "Shfaq Më Shumë Oglase",

		// Product Detail page
		"productDetail.title": "Detajet e Oglasit",
		"productDetail.seller": "Shitësi",
		"productDetail.contact": "Kontakto Shitësin",
		"productDetail.description": "Përshkrimi",
		"productDetail.condition": "Gjendja",
		"productDetail.category": "Kategoria",
		"productDetail.location": "Vendndodhja",
		"productDetail.views": "shikime",
		"productDetail.tags": "Etiketat",
		"productDetail.status": "Statusi",
		"productDetail.status.available": "I Disponueshëm",
		"productDetail.status.sold": "I Shitur",
		"productDetail.status.pending": "Në Pritje",
		"productDetail.backToProducts": "Kthehu te Produktet",
		"productDetail.editProduct": "Ndrysho Oglasin",
		"productDetail.deleteProduct": "Fshi Oglasin",
		"productDetail.confirmDelete":
			"A jeni të sigurt që doni të fshini këtë produkt?",
		"productDetail.deleteSuccess": "Produkti u fshi me sukses",
		"productDetail.deleteError": "Gabim në fshirjen e produktit",

		// Create Product page
		"createProduct.title": "Krijo Oglas të Ri",
		"createProduct.editTitle": "Ndrysho Oglasin",
		"createProduct.form.title": "Titulli i Oglasit",
		"createProduct.form.title.placeholder": "Shkruani titullin e produktit",
		"createProduct.form.description": "Përshkrimi",
		"createProduct.form.description.placeholder":
			"Përshkruani produktin tuaj...",
		"createProduct.form.price": "Çmimi",
		"createProduct.form.currency": "Monedha",
		"createProduct.form.category": "Kategoria",
		"createProduct.form.condition": "Gjendja",
		"createProduct.form.status": "Statusi",
		"createProduct.form.location": "Vendndodhja",
		"createProduct.form.location.placeholder": "Shkruani vendndodhjen",
		"createProduct.form.basicInfo": "Informacioni Bazë",
		"createProduct.form.contactInfo": "Informacioni i Kontaktit",
		"createProduct.form.contactInfo.placeholder":
			"Telefon, email, ose informacion tjetër kontakti",
		"createProduct.form.tags": "Etiketat",
		"createProduct.form.tags.placeholder":
			"Shkruani etiketat të ndara me presje",
		"createProduct.form.images": "Imazhet e Oglasit",
		"createProduct.form.images.upload": "Ngarko Imazhe",
		"createProduct.form.images.remove": "Hiq",
		"createProduct.form.submit": "Krijo Oglasin",
		"createProduct.form.update": "Përditëso Oglasin",
		"createProduct.form.cancel": "Anulo",
		"createProduct.success": "Produkti u krijua me sukses!",
		"createProduct.updateSuccess": "Produkti u përditësua me sukses!",
		"createProduct.error": "Gabim në krijimin e produktit",
		"createProduct.updateError": "Gabim në përditësimin e produktit",
		"createProduct.validation.titleRequired": "Titulli është i detyrueshëm",
		"createProduct.validation.descriptionRequired":
			"Përshkrimi është i detyrueshëm",
		"createProduct.validation.priceRequired": "Çmimi është i detyrueshëm",
		"createProduct.validation.pricePositive": "Çmimi duhet të jetë pozitiv",
		"createProduct.validation.categoryRequired":
			"Kategoria është e detyrueshme",
		"createProduct.validation.conditionRequired": "Gjendja është e detyrueshme",
		"createProduct.validation.locationRequired":
			"Vendndodhja është e detyrueshme",
		"createProduct.invalidPhone":
			"Ju lutemi shkruani një numër telefoni të vlefshëm të Maqedonisë së Veriut (p.sh., +389 XX XXX XXX ose 0XX XXX XXX)",
		"createProduct.invalidPhoneFormat":
			"Ju lutemi shkruani një numër telefoni të vlefshëm të Maqedonisë së Veriut",

		// Category-specific fields
		"createProduct.categoryType.title": "Lloji i Kategorisë",
		"createProduct.categoryType.description":
			"Zgjidhni llojin e oglasit që doni të krijoni për të parë fushat përkatëse",
		"createProduct.categoryType.general": "Oglas i Përgjithshëm",
		"createProduct.categoryType.generalDesc":
			"Formular standard për të gjitha kategoritë",
		"createProduct.categoryType.realEstate": "Pasuri të Paluajtshme",
		"createProduct.categoryType.realEstateDesc":
			"Detajet e pronës, sipërfaqja, adresa, dhoma gjumi",
		"createProduct.categoryType.cars": "Makina dhe Automjete",
		"createProduct.categoryType.carsDesc":
			"Viti, kilometrazhi, lloji i karburantit, transmetimi",

		// Real Estate specific fields
		"createProduct.realEstate.title": "Detajet e Pronës",
		"createProduct.realEstate.propertyType": "Lloji i Pronës",
		"createProduct.realEstate.propertyType.apartment": "Apartament",
		"createProduct.realEstate.propertyType.house": "Shtëpi",
		"createProduct.realEstate.propertyType.land": "Tokë",
		"createProduct.realEstate.propertyType.commercial": "Komercial",
		"createProduct.realEstate.area": "Sipërfaqja (m²)",
		"createProduct.realEstate.area.placeholder": "p.sh., 120",
		"createProduct.realEstate.address": "Adresa e Pronës",
		"createProduct.realEstate.address.placeholder": "Adresa e plotë e pronës",
		"createProduct.realEstate.bedrooms": "Dhoma Gjumi",
		"createProduct.realEstate.bathrooms": "Banjo",

		// Car specific fields
		"createProduct.cars.title": "Detajet e Automjetit",
		"createProduct.cars.year": "Viti",
		"createProduct.cars.year.placeholder": "p.sh., 2020",
		"createProduct.cars.mileage": "Kilometrazhi (km)",
		"createProduct.cars.mileage.placeholder": "p.sh., 50000",
		"createProduct.cars.fuelType": "Lloji i Karburantit",
		"createProduct.cars.fuelType.petrol": "Benzinë",
		"createProduct.cars.fuelType.diesel": "Naftë",
		"createProduct.cars.fuelType.electric": "Elektrike",
		"createProduct.cars.fuelType.hybrid": "Hibrid",
		"createProduct.cars.transmission": "Transmetimi",
		"createProduct.cars.transmission.manual": "Manuale",
		"createProduct.cars.transmission.automatic": "Automatike",
		"createProduct.cars.color": "Ngjyra",
		"createProduct.cars.color.placeholder": "p.sh., Argjendi, E Zezë, E Bardhë",

		// Common select options
		"createProduct.select.propertyType": "Zgjidhni llojin e pronës",
		"createProduct.select.bedrooms": "Zgjidhni dhoma gjumi",
		"createProduct.select.bathrooms": "Zgjidhni banjo",
		"createProduct.select.fuelType": "Zgjidhni llojin e karburantit",
		"createProduct.select.transmission": "Zgjidhni transmetimin",
		"createProduct.select.condition": "Zgjidhni gjendjen",
		"createProduct.select.category": "Zgjidhni kategorinë",

		// Profile page
		"profile.title": "Profili Im",
		"profile.editProfile": "Ndrysho Profilin",
		"profile.saveChanges": "Ruaj Ndryshimet",
		"profile.cancel": "Anulo",
		"profile.personalInfo": "Informacioni Personal",
		"profile.name": "Emri",
		"profile.email": "Email",
		"profile.phone": "Telefoni",
		"profile.location": "Vendndodhja",
		"profile.bio": "Bio",
		"profile.bio.placeholder": "Na tregoni për veten tuaj...",
		"profile.myProducts": "Oglaset e Mia",
		"profile.noProducts": "Nuk keni krijuar ende asnjë produkt",
		"profile.createFirst": "Krijo Produktin tënd të Parë",
		"profile.stats": "Statistikat",
		"profile.totalProducts": "Oglase Gjithsej",
		"profile.totalViews": "Shikime Gjithsej",
		"profile.success": "Profili u përditësua me sukses!",
		"profile.error": "Gabim në përditësimin e profilit",

		// About page
		"about.title": "Rreth NaDlanka",
		"about.subtitle": "Tregu Juaj Lokal",
		"about.mission": "Misioni Ynë",
		"about.mission.text":
			"Të lidhim komunitetet lokale përmes një platforme tregu të thjeshtë, të sigurt dhe të lehtë për t'u përdorur që e bën blerjen dhe shitjen e produkteve të lehtë.",
		"about.features": "Pse të Zgjidhni NaDlanka?",
		"about.feature1.title": "Lokal dhe i Besuar",
		"about.feature1.desc":
			"Lidhuni me njerëzit në komunitetin tuaj për transaksione të sigurta dhe lokale.",
		"about.feature2.title": "Lehtë për t'u Përdorur",
		"about.feature2.desc":
			"Ndërfaqe e thjeshtë e projektuar për të gjithë, pavarësisht nga përvoja teknike.",
		"about.feature3.title": "Plotësisht Falas",
		"about.feature3.desc":
			"Pa tarifa, pa kosto të fshehura. Listoni dhe shikoni produkte falas.",
		"about.feature4.title": "Platformë e Sigurt",
		"about.feature4.desc":
			"Siguria dhe privatësia juaj janë prioritetet tona kryesore.",
		"about.team": "Ekipi Ynë",
		"about.team.text":
			"Jemi një ekip i pasionuar i dedikuar për të ndërtuar përvojën më të mirë të tregut lokal.",
		"about.contact": "Lidhuni me Ne",
		"about.contact.text":
			"Keni pyetje ose sugjerime? Do të donim të dëgjonim nga ju!",
		"about.contact.email": "Na dërgoni email",
		"about.contact.phone": "Na telefononi",
		"about.footer":
			"Bashkohuni me mijëra përdorues që u besojnë NaDlanka për nevojat e tyre të tregut lokal.",

		// Categories
		"categories.all": "Të Gjitha Kategoritë",
		"categories.electronics": "Elektronika",
		"categories.furniture": "Mobilje",
		"categories.cars": "Makinat",
		"categories.realEstate": "Pasuri të Paluajtshme",
		"categories.fashion": "Moda",
		"categories.books": "Libra",
		"categories.sports": "Sporti",
		"categories.homeGarden": "Shtëpi dhe Kopsht",
		"categories.services": "Shërbimet",
		"categories.other": "Të Tjera",

		// Conditions
		"conditions.all": "Të Gjitha Gjendjet",
		"conditions.new": "E Re",
		"conditions.like_new": "Si e Re",
		"conditions.very_good": "Shumë e Mirë",
		"conditions.good": "E Mirë",
		"conditions.fair": "E Pranueshme",
		"conditions.poor": "E Dobët",

		// Form labels
		"form.min": "Min",
		"form.max": "Max",
		"form.enterLocation": "Shkruani vendndodhjen...",
		"form.productsFound": "oglase u gjetën",
		"form.nameAZ": "Emri: A deri në Z",
		"form.by": "Nga",

		// Authentication
		"auth.login.title": "Mirë se vini përsëri",
		"auth.login.subtitle": "Hyni në llogarinë tuaj",
		"auth.login.button": "Hyr",
		"auth.login.noAccount": "Nuk keni llogari?",
		"auth.login.registerLink": "Regjistrohuni",
		"auth.register.title": "Krijo Llogari",
		"auth.register.subtitle": "Bashkohuni me NaDlanka sot",
		"auth.register.button": "Regjistrohu",
		"auth.register.hasAccount": "Keni llogari tashmë?",
		"auth.register.loginLink": "Hyni",
		"auth.register.passwordMismatch": "Fjalëkalimet nuk përputhen",
		"auth.register.passwordTooShort":
			"Fjalëkalimi duhet të jetë të paktën 6 karaktere",
		"auth.email": "Email",
		"auth.password": "Fjalëkalimi",
		"auth.confirmPassword": "Konfirmo Fjalëkalimin",
		"auth.name": "Emri i Plotë",
		"auth.phone": "Numri i Telefonit",
		"auth.location": "Vendndodhja",
		"auth.emailPlaceholder": "Vendosni email-in tuaj",
		"auth.passwordPlaceholder": "Vendosni fjalëkalimin",
		"auth.confirmPasswordPlaceholder": "Konfirmoni fjalëkalimin",
		"auth.namePlaceholder": "Vendosni emrin tuaj të plotë",
		"auth.phonePlaceholder": "Vendosni numrin e telefonit",
		"auth.locationPlaceholder": "Vendosni vendndodhjen",
		"auth.loggingIn": "Duke u futur...",
		"auth.registering": "Duke krijuar llogarinë...",
		"auth.logout": "Dil",
		"auth.google.signIn": "Hyni me Google",
		"auth.google.signUp": "Regjistrohuni me Google",
		"auth.google.continue": "Vazhdoni me Google",

		// Profile
		"profile.addProduct": "Shto Oglas",
		"profile.myProducts": "Oglaset e Mia",
		"profile.statistics": "Statistikat",
		"profile.noProducts": "Nuk ka produkte ende",
		"profile.startSelling":
			"Filloni shitjen duke krijuar listën tuaj të parë të produktit.",
		"profile.createFirstProduct": "Krijo Produktin e Parë",
		"profile.totalProducts": "Produktet Total",
		"profile.activeListings": "Listimet Aktive",
		"profile.totalViews": "Shikimet Total",
		"profile.soldItems": "Artikujt e Shitur",
		"profile.recentActivity": "Aktiviteti i Fundit",
		"profile.noActivity": "Nuk ka aktivitet ende",
		"profile.settings": "Cilësimet",
		"profile.profileSettings": "Cilësimet e Profilit",
		"profile.profileSettingsDesc":
			"Përditësoni informacionin tuaj personal dhe detajet e kontaktit.",
		"profile.invalidPhone":
			"Ju lutemi shkruani një numër telefoni të vlefshëm të Maqedonisë së Veriut (p.sh., +389 XX XXX XXX ose 0XX XXX XXX)",
		"profile.invalidPhoneFormat":
			"Ju lutemi shkruani një numër telefoni të vlefshëm të Maqedonisë së Veriut",
		"profile.updateSuccess": "Profili u përditësua me sukses!",
		"profile.updateError": "Dështoi përditësimi i profilit",
		"profile.locationPlaceholder": "Qyteti, Shteti",

		// Common
		"common.loading": "Duke u ngarkuar...",
		"common.view": "Shiko",
		"common.edit": "Ndrysho",

		// Blog
		"blog.title": "Blogu NaDlanka",
		"blog.subtitle": "Këshilla, udhëzime dhe njohuri për blerjen dhe shitjen",
		"blog.featured": "Postimet e Veçanta",
		"blog.browseByCategory": "Shfletoni sipas Kategorisë",
		"blog.allCategories": "Të Gjitha Kategoritë",
		"blog.categories.tips": "Këshilla dhe Udhëzime",
		"blog.categories.news": "Lajme nga Tregu",
		"blog.categories.stories": "Histori Suksesi",
		"blog.categories.safety": "Siguria dhe Mbrojtja",
		"blog.categories.local": "Lajme Lokale",
		"blog.readMore": "Lexo Më Shumë",
		"blog.likes": "pëlqime",
		"blog.minRead": "min lexim",
		"blog.noPosts": "Nuk u gjetën postime në këtë kategori.",
		"blog.recentPosts": "Postimet e Fundit",
		"blog.categories": "Kategoritë",
		"blog.popularTags": "Etiketat Popullore",
		"blog.newsletter": "Qëndro i Përditësuar",
		"blog.newsletterDesc":
			"Merr këshillat dhe përditësimet e fundit nga tregu direkt në kutinë tënde të postës.",
		"blog.emailPlaceholder": "Shkruaj email-in tënd",
		"blog.subscribe": "Abonohu",
		"blog.error": "Gabim në Ngarkimin e Blogut",
	},

	mk: {
		// Header
		"nav.home": "Дома",
		"nav.products": "Огласи",
		"nav.sell": "Креирај оглас",
		"nav.profile": "Профил",
		"nav.about": "За нас",
		"nav.blog": "Блог",
		"nav.messages": "Пораки",
		"nav.chat": "Разговор",
		"nav.search.placeholder": "Пребарај огласи...",
		"nav.logo.subtitle": "Пазар",

		// Home page
		"home.hero.title": "Добредојдовте во NaDlanka",
		"home.hero.subtitle": "Вашиот локален пазар за купување и продавање огласи",
		"home.hero.browse": "Прегледај Огласи",
		"home.hero.sell": "Продај Нешто",
		"home.stats.products": "Достапни Огласи",
		"home.stats.users": "Активни Корисници",
		"home.stats.free": "Бесплатно за Користење",
		"home.categories.title": "Прелистај по Категорија",
		"home.categories.subtitle": "Најдете токму она што го барате",
		"home.categories.electronics": "Електроника",
		"home.categories.electronicsDesc": "Телефони, лаптопи, гаџети",
		"home.categories.cars": "Автомобили и Возила",
		"home.categories.carsDesc": "Автомобили, мотоцикли, делови",
		"home.categories.realEstate": "Недвижности",
		"home.categories.realEstateDesc": "Станови, куќи, земјиште",
		"home.categories.furniture": "Мебел",
		"home.categories.furnitureDesc": "Домашен и канцелариски мебел",
		"home.categories.fashion": "Мода",
		"home.categories.fashionDesc": "Облека, чевли, аксесоари",
		"home.categories.services": "Услуги",
		"home.categories.servicesDesc": "Професионални услуги",
		"home.exclusive.title": "Ексклузивни Огласи",
		"home.featured.title": "Истакнати Огласи",
		"home.featured.viewAll": "Види Сите →",
		"home.featured.loading": "Се вчитуваат истакнатите огласи...",
		"home.featured.noImage": "Нема Слика",
		"home.howItWorks.title": "Како Функционира NaDlanka",
		"home.howItWorks.step1.title": "Прегледај или Пребарај",
		"home.howItWorks.step1.desc":
			"Најди ги огласите што ги бараш користејќи го нашиот систем за пребарување и филтрирање",
		"home.howItWorks.step2.title": "Контактирај го Продавачот",
		"home.howItWorks.step2.desc":
			"Стапи во контакт со продавачот преку неговите контакт информации",
		"home.howItWorks.step3.title": "Направи Договор",
		"home.howItWorks.step3.desc":
			"Договори и заврши ја твојата трансакција безбедно",
		"home.footer.tagline": "Вашиот локален пазар",
		"home.footer.followUs": "Следете Не",
		"home.footer.rights": "Сите права се задржани.",

		// Common
		"common.loading": "Се вчитува...",
		"common.error": "Грешка",
		"common.success": "Успех",
		"common.save": "Зачувај",
		"common.cancel": "Откажи",
		"common.edit": "Уреди",
		"common.delete": "Избриши",
		"common.view": "Прегледај",
		"common.price": "Цена",
		"common.location": "Локација",
		"common.category": "Категорија",
		"common.condition": "Состојба",
		"common.description": "Опис",
		"common.contact": "Контакт",
		"common.seller": "Продавач",
		"common.status": "Статус",
		"common.views": "Прегледи",
		"common.tags": "Ознаки",
		"common.currency.mkd": "МКД",
		"common.currency.eur": "ЕУР",
		"common.currency.usd": "УСД",
		"common.or": "или",
		"common.phone": "Телефон",
		"common.email": "Е-пошта",
		"common.deleting": "Се брише...",

		// Category pages
		"category.subcategories": "Поткатегории",
		"category.popularSearches": "Популарни пребарувања",
		"category.filters": "Филтри",
		"category.condition": "Состојба",
		"category.allConditions": "Сите состојби",
		"category.new": "Ново",
		"category.likeNew": "Како ново",
		"category.good": "Добро",
		"category.fair": "Прифатливо",
		"category.priceRange": "Опсег на цени",
		"category.minPrice": "Мин",
		"category.maxPrice": "Макс",
		"category.location": "Локација",
		"category.enterLocation": "Внесете локација",
		"category.sortBy": "Сортирај по",
		"category.newestFirst": "Најнови прво",
		"category.oldestFirst": "Најстари прво",
		"category.priceLowToHigh": "Цена: од ниска до висока",
		"category.priceHighToLow": "Цена: од висока до ниска",
		"category.mostPopular": "Најпопуларни",
		"category.clearFilters": "Исчисти ги сите филтри",
		"category.itemsAvailable": "ставки достапни",
		"category.itemAvailable": "ставка достапна",
		"category.noProductsFound": "Не се пронајдени огласи",
		"category.noProductsDesc":
			"Обидете се да ги прилагодите вашите филтри или креирајте оглас за оваа категорија.",
		"category.createListing": "креирајте оглас",
		"category.viewDetails": "Види детали",
		"category.previous": "Претходна",
		"category.next": "Следна",
		"category.page": "Страница",
		"category.of": "од",
		"category.wantToSell": "Сакате да продавате во",
		"category.joinSellers":
			"Придружете се на илјадници продавачи и достигнете повеќе купувачи",
		"category.startSelling": "Започнете да продавате",

		// Category specific translations
		"category.electronics.title": "Електроника",
		"category.electronics.description":
			"Најдете ги најновите паметни телефони, лаптопи, уреди и технолошки додатоци",
		"category.electronics.subcategories.smartphones": "Паметни телефони",
		"category.electronics.subcategories.laptops": "Лаптопи",
		"category.electronics.subcategories.tablets": "Таблети",
		"category.electronics.subcategories.headphones": "Слушалки",
		"category.electronics.subcategories.gaming": "Игри",

		"category.cars.title": "Автомобили и возила",
		"category.cars.description":
			"Купете и продавајте автомобили, мотоцикли и автомобилски додатоци",
		"category.cars.subcategories.cars": "Автомобили",
		"category.cars.subcategories.motorcycles": "Мотоцикли",
		"category.cars.subcategories.trucks": "Камиони",
		"category.cars.subcategories.parts": "Делови",
		"category.cars.subcategories.accessories": "Додатоци",

		"category.realEstate.title": "Недвижности",
		"category.realEstate.description":
			"Станови, куќи и комерцијални имоти за продажба и изнајмување",
		"category.realEstate.subcategories.apartments": "Станови",
		"category.realEstate.subcategories.houses": "Куќи",
		"category.realEstate.subcategories.commercial": "Комерцијални",
		"category.realEstate.subcategories.land": "Земјишта",
		"category.realEstate.subcategories.rentals": "Изнајмување",

		"category.furniture.title": "Мебел",
		"category.furniture.description":
			"Домашен и канцелариски мебел, декорации и домашни предмети",
		"category.furniture.subcategories.livingRoom": "Дневна соба",
		"category.furniture.subcategories.bedroom": "Спална соба",
		"category.furniture.subcategories.kitchen": "Кујна",
		"category.furniture.subcategories.office": "Канцеларија",
		"category.furniture.subcategories.outdoor": "Надвор",

		"category.fashion.title": "Мода и облека",
		"category.fashion.description":
			"Олека, чевли, додатоци и модни предмети за сите сезони",
		"category.fashion.subcategories.mens": "Мажи",
		"category.fashion.subcategories.womens": "Жени",
		"category.fashion.subcategories.kids": "Деца",
		"category.fashion.subcategories.shoes": "Чевли",
		"category.fashion.subcategories.accessories": "Додатоци",

		"category.services.title": "Услуги",
		"category.services.description":
			"Професионални услуги, туторство, фотографија и повеќе",
		"category.services.subcategories.photography": "Фотографија",
		"category.services.subcategories.tutoring": "Туторство",
		"category.services.subcategories.cleaning": "Чистење",
		"category.services.subcategories.repair": "Поправка",
		"category.services.subcategories.delivery": "Доставка",

		"category.sports.title": "Спорт и рекреација",
		"category.sports.description":
			"Спортска опрема, фитнес додатоци и рекреативни активности",
		"category.sports.subcategories.fitness": "Фитнес",
		"category.sports.subcategories.outdoor": "Надвор",
		"category.sports.subcategories.teamSports": "Тимски спортови",
		"category.sports.subcategories.waterSports": "Водни спортови",
		"category.sports.subcategories.winterSports": "Зимски спортови",

		"category.books.title": "Книги и образование",
		"category.books.description":
			"Учебници, романи, образовни материјали и ресурси за учење",
		"category.books.subcategories.textbooks": "Учебници",
		"category.books.subcategories.novels": "Романи",
		"category.books.subcategories.childrens": "Деца",
		"category.books.subcategories.academic": "Академски",
		"category.books.subcategories.language": "Јазик",

		"category.homeGarden.title": "Дом и градина",
		"category.homeGarden.description":
			"Подобрување на домот, градинарски алатки, апарати и домашни предмети",
		"category.homeGarden.subcategories.appliances": "Апарати",
		"category.homeGarden.subcategories.gardenTools": "Градинарски алатки",
		"category.homeGarden.subcategories.kitchen": "Кујна",
		"category.homeGarden.subcategories.bathroom": "Бања",
		"category.homeGarden.subcategories.diy": "Направи сам",

		// Product detail page
		"product.yourListing": "Ова е вашиот оглас",
		"product.status.active": "Активен",
		"product.status.inactive": "Неактивен",
		"product.status.sold": "Продаден",
		"product.yourDetails": "Ваши детали",
		"product.sellerInfo": "Информации за продавачот",
		"product.viewYourProducts": "Види ги вашите огласи",
		"product.viewSellerProducts": "Види ги производите на продавачот",
		"product.backToProducts": "Назад кон огласите",
		"product.contactSeller": "Контактирај го продавачот",
		"product.deactivate": "Деактивирај",
		"product.activate": "Активирај",
		"product.deleteConfirm":
			"Дали сте сигурни дека сакате да го избришете овој производ? Оваа акција не може да се откаже.",
		"product.deletedSuccess": "Производот е успешно избришан",
		"product.deleteError":
			"Неуспешно бришење на производот. Ве молиме обидете се повторно.",
		"product.statusError":
			"Неуспешно ажурирање на статусот на производот. Ве молиме обидете се повторно.",
		"product.posted": "Објавено",
		"product.editProduct": "Уреди го огласот",
		"product.backToProduct": "Назад кон огласот",

		// Contact functionality
		"contact.title": "Контактирај го продавачот",
		"contact.aboutProduct": "За овој производ:",
		"contact.yourName": "Вашето име",
		"contact.yourNamePlaceholder": "Внесете го вашето име",
		"contact.yourEmail": "Вашата е-пошта",
		"contact.yourEmailPlaceholder": "Внесете ја вашата е-пошта",
		"contact.message": "Порака",
		"contact.messagePlaceholder": "Напишете ја вашата порака до продавачот...",
		"contact.sendMessage": "Испрати порака",
		"contact.sending": "Се испраќа...",
		"contact.messageSent": "Пораката е испратена!",
		"contact.messageSentDesc": "Вашата порака е испратена до продавачот.",
		"contact.chooseMethod": "Како сакате да го контактирате продавачот?",
		"contact.methodDescription":
			"Изберете помеѓу директни разговор или е-пошта:",
		"contact.liveChat": "Директни Разговор",
		"contact.liveChatDesc": "Инстант пораки со реални време известувања",
		"contact.startChat": "Започни Директни Разговор",
		"contact.chatDesc": "Разговарај во реално време со продавачот",
		"contact.chatError":
			"Не успеа да се започне разговорот. Ве молиме обидете се повторно.",
		"contact.loginForChat":
			"Ве молиме најавете се за да користите директни разговор",
		"contact.sendEmail": "Испрати е-пошта",
		"contact.emailDesc":
			"Испрати порака преку е-пошта (продавачот ќе биде известен)",
		"contact.call": "Телефонирај",
		"contact.whatsapp": "WhatsApp",
		"contact.loginNotice":
			"Треба да бидете најавени за да користите директни разговор.",

		// Favorites functionality
		"favorites.title": "Мои омилени",
		"favorites.addToFavorites": "Додај во омилени",
		"favorites.removeFromFavorites": "Отстрани од омилени",
		"favorites.save": "Зачувај",
		"favorites.saved": "Зачувано",
		"favorites.noFavorites": "Сè уште нема омилени",
		"favorites.noFavoritesDesc":
			"Започнете со зачувување на вашите омилени огласи за лесно да ги најдете подоцна.",
		"favorites.browseCatalogue": "Прелистај каталог",
		"favorites.error": "Неуспешно ажурирање на омилени",
		"favorites.loading": "Се вчитуваат омилени...",
		"favorites.totalFavorites": "Вкупно омилени",
		"favorites.viewAll": "Види ги сите омилени",
		"favorites.loginToView":
			"Ве молиме најавете се за да ги видите вашите омилени",
		"auth.loginRequired": "Потребна е најава",
		"auth.signIn": "Најави се",

		// Chat functionality
		"chat.title": "Разговор",
		"chat.selectChat": "Изберете разговор за да започнете пораки",
		"chat.selectChatDesc":
			"Изберете разговор од страничната лента за да започнете да разговарате.",
		"chat.newChat": "Нов Разговор",
		"chat.search": "Пребарај разговори...",
		"chat.noChats": "Не се пронајдени разговори",
		"chat.clearSearch": "Исчисти пребарување",
		"chat.about": "За",
		"chat.noMessages": "Сè уште нема пораки",
		"chat.typing": "пишува...",
		"chat.typeMessage": "Напишете порака...",
		"chat.loginRequired": "Ве молиме најавете се за да користите разговор",
		"chat.loginRequiredDesc":
			"Треба да бидете најавени за да испраќате и примате пораки.",

		// Messages/Inbox functionality
		"messages.title": "Ваши пораки",
		"messages.all": "Сите пораки",
		"messages.unread": "Непрочитани",
		"messages.read": "Прочитани",
		"messages.replied": "Одговорени",
		"messages.noMessages": "Не се пронајдени пораки",
		"messages.selectMessage": "Изберете порака за да ги видите деталите",
		"messages.contactInfo": "Информации за контакт",
		"messages.preferredContact": "Префериран контакт",
		"messages.message": "Порака",
		"messages.reply": "Одговори",
		"messages.replyInstruction":
			"Одговорете директно на оваа е-пошта за да го контактирате купувачот.",
		"messages.replyEmail": "Одговори преку е-пошта",
		"messages.markReplied": "Означи како одговорено",
		"product.basicInfo": "Основни информации",
		"product.titlePlaceholder": "Внесете наслов на огласот",
		"product.descriptionPlaceholder": "Опишете го вашиот производ",
		"product.selectCategory": "Изберете категорија",
		"product.selectCondition": "Изберете состојба",
		"product.additionalInfo": "Дополнителни информации",
		"product.locationPlaceholder": "Внесете локација",
		"product.tagsPlaceholder": "Внесете ознаки разделени со запирки",
		"product.tagsHelp":
			"Разделете ги ознаките со запирки (на пр., vintage, електроника, игри)",
		"product.currentImages": "Тековни слики",
		"product.backToProfile": "Назад кон профилот",
		"product.updatedSuccess": "Производот е успешно ажуриран",
		"product.updateError":
			"Неуспешно ажурирање на производот. Ве молиме обидете се повторно.",
		"common.saving": "Се зачувува...",

		// Ads page (Products/CreateProduct pages)
		"products.title": "Сите Огласи",
		"products.search.placeholder": "Пребарај огласи...",
		"products.filter.category": "Категорија",
		"products.filter.condition": "Состојба",
		"products.filter.priceRange": "Ценовен Опсег",
		"products.filter.location": "Локација",
		"products.filter.sortBy": "Сортирај по",
		"products.filter.sortBy.newest": "Најнови",
		"products.filter.sortBy.oldest": "Најстари",
		"products.filter.sortBy.priceLow": "Цена: Од ниска до висока",
		"products.filter.sortBy.priceHigh": "Цена: Од висока до ниска",
		"products.filter.sortBy.views": "Најгледани",
		"products.filter.clear": "Исчисти Филтри",
		"products.noResults": "Не се пронајдени огласи",
		"products.loading": "Се вчитуваат производите...",
		"products.error": "Грешка при вчитување на огласите",
		"products.pagination.previous": "Претходна",
		"products.pagination.next": "Следна",
		"products.pagination.page": "Страница",
		"products.pagination.of": "од",
		"products.showMore": "Прикажи Повеќе Огласи",

		// Product Detail page
		"productDetail.title": "Детали за Огласот",
		"productDetail.seller": "Продавач",
		"productDetail.contact": "Контактирај го Продавачот",
		"productDetail.description": "Опис",
		"productDetail.condition": "Состојба",
		"productDetail.category": "Категорија",
		"productDetail.location": "Локација",
		"productDetail.views": "прегледи",
		"productDetail.tags": "Ознаки",
		"productDetail.status": "Статус",
		"productDetail.status.available": "Достапен",
		"productDetail.status.sold": "Продаден",
		"productDetail.status.pending": "Во чекање",
		"productDetail.backToProducts": "Назад кон Производите",
		"productDetail.editProduct": "Уреди Оглас",
		"productDetail.deleteProduct": "Избриши Оглас",
		"productDetail.confirmDelete":
			"Дали сте сигурни дека сакате да го избришете овој производ?",
		"productDetail.deleteSuccess": "Производот е успешно избришан",
		"productDetail.deleteError": "Грешка при бришење на огласот",

		// Create Product page
		"createProduct.title": "Креирај Нов Оглас",
		"createProduct.editTitle": "Уреди Оглас",
		"createProduct.form.title": "Наслов на Огласот",
		"createProduct.form.title.placeholder": "Внесете го насловот на огласот",
		"createProduct.form.description": "Опис",
		"createProduct.form.description.placeholder":
			"Опишете го вашиот производ...",
		"createProduct.form.price": "Цена",
		"createProduct.form.currency": "Валута",
		"createProduct.form.category": "Категорија",
		"createProduct.form.condition": "Состојба",
		"createProduct.form.status": "Статус",
		"createProduct.form.location": "Локација",
		"createProduct.form.location.placeholder": "Внесете локација",
		"createProduct.form.basicInfo": "Основни Информации",
		"createProduct.form.contactInfo": "Контакт Информации",
		"createProduct.form.contactInfo.placeholder":
			"Телефон, е-пошта или други контакт информации",
		"createProduct.form.tags": "Ознаки",
		"createProduct.form.tags.placeholder": "Внесете ознаки одделени со запирка",
		"createProduct.form.images": "Слики на Огласот",
		"createProduct.form.images.upload": "Прикачи Слики",
		"createProduct.form.images.remove": "Отстрани",
		"createProduct.form.submit": "Креирај Оглас",
		"createProduct.form.update": "Ажурирај Оглас",
		"createProduct.form.cancel": "Откажи",
		"createProduct.success": "Производот е успешно креиран!",
		"createProduct.updateSuccess": "Производот е успешно ажуриран!",
		"createProduct.error": "Грешка при креирање на огласот",
		"createProduct.updateError": "Грешка при ажурирање на огласот",
		"createProduct.validation.titleRequired": "Насловот е задолжителен",
		"createProduct.validation.descriptionRequired": "Описот е задолжителен",
		"createProduct.validation.priceRequired": "Цената е задолжителна",
		"createProduct.validation.pricePositive": "Цената мора да биде позитивна",
		"createProduct.validation.categoryRequired": "Категоријата е задолжителна",
		"createProduct.validation.conditionRequired": "Состојбата е задолжителна",
		"createProduct.validation.locationRequired": "Локацијата е задолжителна",
		"createProduct.invalidPhone":
			"Ве молиме внесете валиден телефонски број од Северна Македонија (на пр., +389 XX XXX XXX или 0XX XXX XXX)",
		"createProduct.invalidPhoneFormat":
			"Ве молиме внесете валиден телефонски број од Северна Македонија",

		// Category-specific fields
		"createProduct.categoryType.title": "Тип на Категорија",
		"createProduct.categoryType.description":
			"Изберете го типот на оглас што сакате да го креирате за да ги видите релевантните полиња",
		"createProduct.categoryType.general": "Општ Оглас",
		"createProduct.categoryType.generalDesc":
			"Стандардна форма за сите категории",
		"createProduct.categoryType.realEstate": "Недвижности",
		"createProduct.categoryType.realEstateDesc":
			"Детали за имотот, површина, адреса, спални соби",
		"createProduct.categoryType.cars": "Автомобили и Моторни Возила",
		"createProduct.categoryType.carsDesc":
			"Година, километража, тип на гориво, менувач",

		// Real Estate specific fields
		"createProduct.realEstate.title": "Детали за Имотот",
		"createProduct.realEstate.propertyType": "Тип на Имот",
		"createProduct.realEstate.propertyType.apartment": "Стан",
		"createProduct.realEstate.propertyType.house": "Куќа",
		"createProduct.realEstate.propertyType.land": "Парцела",
		"createProduct.realEstate.propertyType.commercial": "Комерцијална",
		"createProduct.realEstate.area": "Површина (m²)",
		"createProduct.realEstate.area.placeholder": "нпр., 120",
		"createProduct.realEstate.address": "Адреса на Имотот",
		"createProduct.realEstate.address.placeholder": "Полна адреса на имотот",
		"createProduct.realEstate.bedrooms": "Спални Соби",
		"createProduct.realEstate.bathrooms": "Бањи",

		// Car specific fields
		"createProduct.cars.title": "Детали за Возилото",
		"createProduct.cars.year": "Година",
		"createProduct.cars.year.placeholder": "нпр., 2020",
		"createProduct.cars.mileage": "Километража (km)",
		"createProduct.cars.mileage.placeholder": "нпр., 50000",
		"createProduct.cars.fuelType": "Тип на Гориво",
		"createProduct.cars.fuelType.petrol": "Бензин",
		"createProduct.cars.fuelType.diesel": "Дизел",
		"createProduct.cars.fuelType.electric": "Електрично",
		"createProduct.cars.fuelType.hybrid": "Хибридно",
		"createProduct.cars.transmission": "Менувач",
		"createProduct.cars.transmission.manual": "Мануелен",
		"createProduct.cars.transmission.automatic": "Автоматски",
		"createProduct.cars.color": "Боја",
		"createProduct.cars.color.placeholder": "нпр., Сребрена, Црна, Бела",

		// Common select options
		"createProduct.select.propertyType": "Изберете тип на имот",
		"createProduct.select.bedrooms": "Изберете спални соби",
		"createProduct.select.bathrooms": "Изберете бањи",
		"createProduct.select.fuelType": "Изберете тип на гориво",
		"createProduct.select.transmission": "Изберете менувач",
		"createProduct.select.condition": "Изберете состојба",
		"createProduct.select.category": "Изберете категорија",

		// Profile page
		"profile.title": "Мој Профил",
		"profile.editProfile": "Уреди Профил",
		"profile.saveChanges": "Зачувај Промени",
		"profile.cancel": "Откажи",
		"profile.personalInfo": "Лични Информации",
		"profile.name": "Име",
		"profile.email": "Е-пошта",
		"profile.phone": "Телефон",
		"profile.location": "Локација",
		"profile.bio": "Био",
		"profile.bio.placeholder": "Кажете ни за себе...",
		"profile.myProducts": "Мои Огласи",
		"profile.noProducts": "Сè уште не сте креирале огласи",
		"profile.createFirst": "Креирај го Вашиот Прв Производ",
		"profile.stats": "Статистики",
		"profile.totalProducts": "Вкупно Огласи",
		"profile.totalViews": "Вкупно Прегледи",
		"profile.success": "Профилот е успешно ажуриран!",
		"profile.error": "Грешка при ажурирање на профилот",

		// About page
		"about.title": "За NaDlanka",
		"about.subtitle": "Вашиот Локален Пазар",
		"about.mission": "Нашата Мисија",
		"about.mission.text":
			"Да ги поврземе локалните заедници преку една едноставна, безбедна и лесно употреблива платформа за пазар што ја прави купувањето и продавањето на производи лесно.",
		"about.features": "Зошто да го Изберете NaDlanka?",
		"about.feature1.title": "Локален и Доверлив",
		"about.feature1.desc":
			"Поврзете се со луѓето во вашата заедница за безбедни, локални трансакции.",
		"about.feature2.title": "Лесно за Користење",
		"about.feature2.desc":
			"Едноставен интерфејс дизајниран за сите, без разлика на техничкото искуство.",
		"about.feature3.title": "Целосно Бесплатно",
		"about.feature3.desc":
			"Без такси, без скриени трошоци. Листајте и прегледувајте производи бесплатно.",
		"about.feature4.title": "Безбедна Платформа",
		"about.feature4.desc":
			"Вашата безбедност и приватност се нашите главни приоритети.",
		"about.team": "Нашиот Тим",
		"about.team.text":
			"Ние сме страствен тим посветен на градење на најдоброто искуство за локален пазар.",
		"about.contact": "Контактирајте Не",
		"about.contact.text":
			"Имате прашања или предлози? Би сакале да слушнеме од вас!",
		"about.contact.email": "Испратете ни е-пошта",
		"about.contact.phone": "Телефонирајте ни",
		"about.footer":
			"Придружете се на илјадници корисници кои му веруваат на NaDlanka за нивните потреби за локален пазар.",

		// Categories
		"categories.all": "Сите Категории",
		"categories.electronics": "Електроника",
		"categories.furniture": "Мебел",
		"categories.cars": "Автомобили",
		"categories.realEstate": "Недвижности",
		"categories.fashion": "Мода",
		"categories.books": "Книги",
		"categories.sports": "Спорт",
		"categories.homeGarden": "Дом и Градина",
		"categories.services": "Услуги",
		"categories.other": "Друго",

		// Conditions
		"conditions.all": "Сите Состојби",
		"conditions.new": "Ново",
		"conditions.like_new": "Како Ново",
		"conditions.very_good": "Многу Добро",
		"conditions.good": "Добро",
		"conditions.fair": "Прифатливо",
		"conditions.poor": "Слабо",

		// Form labels
		"form.min": "Мин",
		"form.max": "Макс",
		"form.enterLocation": "Внесете локација...",
		"form.productsFound": "огласи пронајдени",
		"form.nameAZ": "Име: А до Ш",
		"form.by": "Од",

		// Authentication
		"auth.login.title": "Добредојдовте назад",
		"auth.login.subtitle": "Најавете се на вашата сметка",
		"auth.login.button": "Најави се",
		"auth.login.noAccount": "Немате сметка?",
		"auth.login.registerLink": "Регистрирај се",
		"auth.register.title": "Креирај сметка",
		"auth.register.subtitle": "Придружете се на NaDlanka денеска",
		"auth.register.button": "Регистрирај се",
		"auth.register.hasAccount": "Веќе имате сметка?",
		"auth.register.loginLink": "Најави се",
		"auth.register.passwordMismatch": "Лозинките не се совпаѓаат",
		"auth.register.passwordTooShort":
			"Лозинката мора да биде најмалку 6 карактери",
		"auth.email": "Е-пошта",
		"auth.password": "Лозинка",
		"auth.confirmPassword": "Потврди лозинка",
		"auth.name": "Полно име",
		"auth.phone": "Телефонски број",
		"auth.location": "Локација",
		"auth.emailPlaceholder": "Внесете ја вашата е-пошта",
		"auth.passwordPlaceholder": "Внесете ја вашата лозинка",
		"auth.confirmPasswordPlaceholder": "Потврдете ја лозинката",
		"auth.namePlaceholder": "Внесете го вашето полно име",
		"auth.phonePlaceholder": "Внесете го вашиот телефонски број",
		"auth.locationPlaceholder": "Внесете ја вашата локација",
		"auth.loggingIn": "Се најавувам...",
		"auth.registering": "Креирам сметка...",
		"auth.logout": "Одјави се",
		"auth.google.signIn": "Најави се со Google",
		"auth.google.signUp": "Регистрирај се со Google",
		"auth.google.continue": "Продолжи со Google",

		// Profile
		"profile.addProduct": "Додај оглас",
		"profile.myProducts": "Мои огласи",
		"profile.statistics": "Статистики",
		"profile.noProducts": "Сè уште нема огласи",
		"profile.startSelling":
			"Започнете со продажба со создавање на вашата прва листа на производи.",
		"profile.createFirstProduct": "Создај го првиот производ",
		"profile.totalProducts": "Вкупно огласи",
		"profile.activeListings": "Активни листи",
		"profile.totalViews": "Вкупно прегледи",
		"profile.soldItems": "Продадени ставки",
		"profile.recentActivity": "Неодамнешна активност",
		"profile.noActivity": "Сè уште нема активност",
		"profile.settings": "Поставки",
		"profile.profileSettings": "Поставки на профилот",
		"profile.profileSettingsDesc":
			"Ажурирајте ги вашите лични информации и детали за контакт.",
		"profile.invalidPhone":
			"Ве молиме внесете валиден телефонски број од Северна Македонија (на пр., +389 XX XXX XXX или 0XX XXX XXX)",
		"profile.invalidPhoneFormat":
			"Ве молиме внесете валиден телефонски број од Северна Македонија",
		"profile.updateSuccess": "Профилот е успешно ажуриран!",
		"profile.updateError": "Неуспешно ажурирање на профилот",
		"profile.locationPlaceholder": "Град, Држава",

		// Common
		"common.loading": "Се вчитува...",
		"common.view": "Види",
		"common.edit": "Уреди",

		// Blog
		"blog.title": "НаДланка Блог",
		"blog.subtitle": "Совети, водичи и инсајти за купување и продавање",
		"blog.featured": "Истакнати Објави",
		"blog.browseByCategory": "Прелистај по Категорија",
		"blog.allCategories": "Сите Категории",
		"blog.categories.tips": "Совети и Водичи",
		"blog.categories.news": "Новости од Пазарот",
		"blog.categories.stories": "Приказни за Успех",
		"blog.categories.safety": "Безбедност и Заштита",
		"blog.categories.local": "Локални Новости",
		"blog.readMore": "Прочитај Повеќе",
		"blog.likes": "лајкови",
		"blog.minRead": "мин читање",
		"blog.noPosts": "Не се пронајдени објави во оваа категорија.",
		"blog.recentPosts": "Неодамнешни Објави",
		"blog.categories": "Категории",
		"blog.popularTags": "Популарни Тагови",
		"blog.newsletter": "Остани Информиран",
		"blog.newsletterDesc":
			"Добијте најнови совети и пазарни ажурирања директно во вашата поштенска кутија.",
		"blog.emailPlaceholder": "Внесете ја вашата е-пошта",
		"blog.subscribe": "Претплати се",
		"blog.error": "Грешка при вчитување на блогот",
	},
};

const languageNames = {
	en: "English",
	sq: "Shqip",
	mk: "Македонски",
};

const languageFlags = {
	en: "🇺🇸",
	sq: "🇦🇱",
	mk: "🇲🇰",
};

export const LanguageProvider = ({ children }) => {
	const [currentLanguage, setCurrentLanguage] = useState(() => {
		const savedLanguage = localStorage.getItem("language");
		return savedLanguage && translations[savedLanguage] ? savedLanguage : "en";
	});

	useEffect(() => {
		localStorage.setItem("language", currentLanguage);
	}, [currentLanguage]);

	const t = (key) => {
		return translations[currentLanguage]?.[key] || translations.en[key] || key;
	};

	const changeLanguage = (languageCode) => {
		if (translations[languageCode]) {
			setCurrentLanguage(languageCode);
		}
	};

	const getAvailableLanguages = () => {
		return Object.keys(translations).map((code) => ({
			code,
			name: languageNames[code],
			flag: languageFlags[code],
		}));
	};

	const value = {
		currentLanguage,
		changeLanguage,
		t,
		getAvailableLanguages,
	};

	return (
		<LanguageContext.Provider value={value}>
			{children}
		</LanguageContext.Provider>
	);
};
